### PR TITLE
20.5.0 release notes

### PR DESCRIPTION
**Pull request by maheshp**
20.5.0 release notes

### CODE REVIEW

**Comment by arvindsv** [comment]
@maheshp I've added a commit with a few small changes.

**Comment by varshavaradarajan** [comment]
Do we not want to mention the supported Pg and MySQL version?

**Comment by arvindsv** [comment]
It's called out in pages such as this: https://docs.gocd.org/20.5.0/installation/configuring_database/postgres.html

... but it's probably a good idea to mention it here and in https://docs.gocd.org/20.5.0/installation/upgrade_to_gocd_20.5.0.html

**Comment by arvindsv** [comment]
No, actually. Only here: https://docs.gocd.org/20.5.0/installation/configuring_database.html

**Pull request merged**
