### PR TITLE
Change to miller projection for map

### PR DESCRIPTION
**Pull request by arvindsv**
@naveenbhaskar: I think this projection looks better. See an example [here](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/basic/multiple_projections.html).

However, because it takes the whole page and the scroll button scrolls the map, there is a risk of someone thinking there's no content on this page. Might want to consider moving some content above the map?

Also, updates to mapael-2.0.0.

cc: @nyuday - You might have some thoughts too.

### CODE REVIEW

**Comment by arvindsv** [comment]
Old:

screen shot 2016-07-14 at 12 13 55 pm

New:

screen shot 2016-07-14 at 12 13 47 pm

**Comment by nyuday** [comment]
I like the projection. @arvindsv - agree with you on moving the content upwards a bit. Have a thought though and perhaps this is because I haven't seen the copy below. I am not sure it is completely obvious to people what the map is. So before we start the copy, might be useful to have a caption/title for the map? E.g. "GoCD Global Contributor Community"

**Comment by arvindsv** [comment]
Sure. Go to town with it! :)

**Comment by naveenbhaskar** [comment]
Should we move the map to the bottom? I feel the content is more important than map in that page?

I have added the title "GoCD Global Contributor Community" to the map.

**Comment by nyuday** [comment]
Sounds like a good idea. Might be worth taking a look for sure. 

-- 

Lubaina Rangwala

+91 9741381384

@lubaina

On Tue, Jul 19, 2016 at 12:00 PM NaveenBhaskar

<
mailto:NaveenBhaskar <notifications@github.com>
> wrote:

Should we move the map to the bottom? I feel the content is more important than map in that page?

I have added the title "GoCD Global Contributor Community" to the map.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/gocd/www.go.cd/pull/310#issuecomment-233543750
, or

**Comment by ketan** [comment]
@arvindsv closing. please rebase and re-open if this is still relevant

**Pull request closed without merging**
