### PR TITLE
Added gitlab(ce) oauth plugin

### PR DESCRIPTION
**Pull request by selvakn**

### CODE REVIEW

**Comment by ketan** [comment]
Hi, any reason to not submit a PR to the upstream oauth plugin repo, that repo is maintained fairly well by the community.

**Comment by selvakn** [comment]
I had to diverge a lot, because the `social-auth` did not support gitlab in a straightforward way and my fork uses `scribejava`, which seem to be better maintained.

But unfortunately, I had to break compatibility with google login. 

If you/community is ok with the above changes, Im happy to work on google login as well and merge it back.

**Comment by ketan** [comment]
It'd be nice if there was one repository for all OAuth plugins, I'm happy to provide you commit access to the gocd-oauth-plugins, should you want to maintain the gitlab integration bits :)

Coming to social-auth library, it appears to be straight forward to register your [own provider](https://github.com/3pillarlabs/socialauth/blob/3a49628fb30a641923a1405b00f8e7d480490bfb/socialauth/src/main/java/org/brickred/socialauth/SocialAuthConfig.java#L177-L181) for GitLab, the implementation looks straight forward too — https://github.com/3pillarlabs/socialauth/blob/3a49628fb30a641923a1405b00f8e7d480490bfb/socialauth/src/main/java/org/brickred/socialauth/provider/GitHubImpl.java.

[The configuration](https://github.com/3pillarlabs/socialauth/blob/3a49628fb30a641923a1405b00f8e7d480490bfb/socialauth/src/main/java/org/brickred/socialauth/provider/GitHubImpl.java#L94-L119) allows connecting to not just github.com, but also a github enterprise instance, I'm sure it'd be fairly similar for GitLab.

Of course you don't have to do all of this, and I could just merge this PR as is. But it'd be nice if we could work together to manage some of the oauth plugins :)

**Comment by ketan** [comment]
Let me know if you want me to merge this AS-IS :)

**Comment by selvakn** [comment]
Sent a [pull request](https://github.com/gocd-contrib/gocd-oauth-login/pull/39) to the upstream oauth plugin repo.

Happy to maintain this plugin and others going forward :)

**Pull request merged**
