### PR TITLE
Added new webinars section under events page

### PR DESCRIPTION
**Pull request by markandan**

### CODE REVIEW

**Comment by ketan** [comment]
> Updated the Webinar section with dummy data

Is this intentional?

**Comment by nyuday** [comment]
Yes. Wanted to see what it looked like before we move it live. I'll be
filling in the dates today.

**Comment by ketan** [comment]
@nyuday — the PR looks good to me. Merge it once the dates are in place.

**Comment by markandan** [comment]
One of the external link in the following blog post is not working so the build is failing. Kindly let me know what needs to be done

Link : https://www.go.cd/2014/02/24/deploy-package-not-just-tag-branch-or-binary/

**Pull request closed without merging**
