### PR TITLE
Guest post: Your first Pipeline with GoCD

### PR DESCRIPTION
**Pull request by moritz**
Hi, this my first attempt at a guest post, so please be gentle. Feedback of all kinds very welcome.

### CODE REVIEW

**Comment by moritz** [comment]
Hi everybody, got any updates for me? Is there anything I can do to get a review and/or merge?

**Comment by arvindsv** [comment]
Hi @moritz: Sorry about the delay. I'll work with you on this and help get this merged soon.

My current concern about this is that it has a very generic title with some very specific content. We should probably think about changing the title. I like the part where it talks about the incrementing version. I'm thinking about adding a couple of images as well, to show that there was a pipeline with one material, and then the scripts were checked in into a different repository.

**Comment by moritz** [comment]
Hi @arvindsv,

I'm fine with a more specific title. Maybe "Managing Build Versions in your GoCD Pipeline"?

Graphics would also be nice, that's not really a strength of mine :-)

Cheers,
Moritz

**Comment by arvindsv** [comment]
I see you changed it. I think it feels better as a title. The images are not my strength as well, but I can draw something which at least conveys some meaning. Maybe I can get some help from someone else too.

**Comment by moritz** [comment]
Thanks @arvindsv, that would be appreciated.

**Comment by nyuday** [comment]
@moritz - Sorry it took this long to get this merged. We'll be making a couple of modifications (on the date of the post and title, some spelling and formatting addition) before we publish it. I'll share it with you before we make it public.

**Pull request merged**
